package carboniferous.core.handlers;

import java.util.Arrays;

import carboniferous.api.Properties;
import carboniferous.lib.Reference;
import cpw.mods.fml.common.ModMetadata;

/**
 * @author ProPercivalalb
 **/
public class ModMetadataHandler {

	public static void redoModMetadata(ModMetadata meta) {
		meta.modId         = Reference.MOD_ID;
		meta.name          = Reference.MOD_NAME;
		meta.version       = Reference.MOD_VERSION;
		meta.authorList    = Arrays.asList("ProPercivalalb");
		meta.description   = "Go back 360 million years in the past into the Carboniferous era. Where the oxygen is double what it is today. This resulted in hyper plant growth and hyper insect growth. Step through the time travel portal and prepare for what lies ahead!";
		meta.url           = "Unreleased, url will be here soon!";
		meta.credits       = "ProPercivalalb, Dylan4Ever, IHVD, others. Based on the Pre-Pre Historic Mod";
		meta.logoFile	   = Properties.TEX_LOGO;
		meta.autogenerated = false;
	}
}
